#!/bin/sh

set -C -f
IFS="$(printf '%b_' '\n')"
IFS="${IFS%_}"

PREVIEW_WIDTH=600 # px

# TODO: Render in the original width when it's smaller than PREVIEW_WIDTH

# Prevent recursive thumbnails (if the file ends in .six)
[ "${1##*.}" = "six" ] && cat "$1" && exit 1

case "$(file --dereference --brief --mime-type -- "$1")" in
text/html)
	lynx -width="$4" -display_charset=utf-8 -dump "$1"
	;;
text/troff)
	man ./ "$1" | col -b
	;;
text/* | */xml | application/json | application/x-ndjson)
  /opt/homebrew/bin/bat --terminal-width "$(($4 - 2))" -f "$1"
	;;
audio/* | application/octet-stream)
	mediainfo "$1" || exit 1
	;;
image/vnd.djvu)
		djvused "$1" -e 'select 1; save-page-with /dev/stdout' |
			convert djvu:- ppm:- | \
      chafa -t 0.9 -f sixels --optimize 9 --color-space din99d -c full -w 9 --size "$(($4 -2))"x --polite on
			# img2sixel -S -E size -q high -w $PREVIEW_WIDTH "$1"
	;;
image/webp)
  dwebp "$1" -tiff -o - | \
    chafa -t 0.9 -f sixels --optimize 9 --color-space din99d -c full -w 9 --size "$(($4 -2))"x --polite on
    # img2sixel -S -E size -q high -w $PREVIEW_WIDTH "$1"
	;;
image/heic)
		# convert "$1" ppm:- |
    chafa -t 0.9 -f sixels --optimize 9 --color-space din99d -c full -w 9 --size "$(($4 -2))"x --polite on "$1"
      # img2sixel -S -E size -q high -w $PREVIEW_WIDTH "$1"
	;;
image/*)
    chafa -t 0.9 -f sixels --optimize 9 --color-space din99d -c full -w 9 --size "$(($4 -2))"x --polite on "$1"
		# img2sixel -S -E size -q high -w $PREVIEW_WIDTH "$1"
	;;
*/pdf)
		pdftocairo -singlefile -scale-to-x $PREVIEW_WIDTH -scale-to-y -1 -jpeg "$1" - |
      chafa -t 0.9 -f sixels --optimize 9 --color-space din99d -c full -w 9 --size "$(($4 -2))"x --polite on
      # img2sixel -S -E size -q high "$1"
	;;
video/*)
		ffmpegthumbnailer -i "$1" -s 0 -c jpeg -f -o - |
      chafa -t 0.9 -f sixels --optimize 9 --color-space din99d -c full -w 9 --size "$(($4 -2))"x --polite on
      # img2sixel -S -E size -q high -w $PREVIEW_WIDTH "$1"
	;;
application/*zip)
	atool --list -- "$1"
	;;
*spreadsheetml.sheet)
	xlsx2csv -s 1 "$1" | /opt/homebrew/bin/bat --terminal-width "$(($4 - 2))" -l 'csv'
	;;
*opendocument*)
	odt2txt "$1"
	;;
application/pgp-encrypted)
	gpg -d -- "$1"
	;;
esac

exit 1
