[manager]
prepend_keymap = [
  { on = ["g", "cp"], run = "cd ~/.local/src" },
  { on = ["g", "CP"], run = "cd ~/.local/src" },
  { on = ["g", "cf"], run = "cd ~/.config" },
  { on = ["g", "CF"], run = "cd ~/.config" },
  { on = ["g", "dl"], run = "cd ~/Downloads" },
  { on = ["g", "DL"], run = "cd ~/Downloads" },
  { on = ["g", "sx"], run = "cd ~/.config/sxhkd" },
  { on = ["g", "SX"], run = "cd ~/.config/sxhkd" },
  { on = ["g", "vi"], run = "cd ~/.config/nvim" },
  { on = ["g", "VI"], run = "cd ~/.config/nvim" },
  { on = ["g", "sc"], run = "cd ~/.local/bin" },
  { on = ["g", "SC"], run = "cd ~/.local/bin" },
  { on = ["g", "ui"], run = "cd ~/University/2026_S4/" },
  { on = ["g", "UI"], run = "cd ~/University/2026_S4/" },
  { on = ["g", "wm"], run = "cd ~/.local/src/dwm" },
  { on = ["g", "WM"], run = "cd ~/.local/src/dwm" },
  { on = ["g", "ws"], run = "cd ~/Workspace" },
  { on = ["g", "WS"], run = "cd ~/Workspace" },
]
