
[bell]
animation = "EaseOutExpo"
color = "#7d4b23"
duration = 200

[colors.bright]
black = "0x868b8d"
blue = "0x779988"
cyan = "0x66aabb"
green = "0x037500"
magenta = "0x738c9c"
red = "0x810002"
white = "0xc0c7ca"
yellow = "0xebcb88"

[colors.normal]
black = "0x111a1f"
blue = "0x63768a"
cyan = "0x6998b3"
green = "0x798362"
magenta = "0xb7416e"
red = "0x8d7856"
white = "0xc5c8c6"
yellow = "0x9b9257"

[colors.primary]
background = "0x111a1f"
foreground = "0xacb3b5"

# [cursor]
# blinking = "Off"
# shape = "Block"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
# draw_bold_text_with_bright_colors = false
size = 11

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Alt|Shift"

[mouse]
hide_when_typing = true

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 10000

[window]
dynamic_title = true
opacity = 0.74
title = "Terminal"

[window.class]
general = "AlacrittyApp"
instance = "Alacritty"

[window.padding]
x = 6
y = 18
